// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"
	"time"

	test "sse-demo/service/sse-demo/internal/handler/test"
	"sse-demo/service/sse-demo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Test
				Method:  http.MethodGet,
				Path:    "/test",
				Handler: test.TestHandler(serverCtx),
			},
		},
		rest.WithPrefix("/test"),
		rest.WithTimeout(10000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Test2
				Method:  http.MethodGet,
				Path:    "/test2",
				Handler: test.Test2Handler(serverCtx),
			},
		},
		rest.WithPrefix("/test"),
		rest.WithTimeout(5000*time.Millisecond),
	)
}
